# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-04 07:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=20)),
            ],
            options={
                'ordering': ('route',),
            },
        ),
    ]
