# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(default='null', upload_to='images')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
