# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Event',
        ),
    ]
