# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_description',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
