# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20180412_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(upload_to='multimedia/static/'),
        ),
    ]
