# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180414_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
    ]
