# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20180404_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('stop', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('day',)},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(),
        ),
    ]
