# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import bus.myFields


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', bus.myFields.DayOfTheWeekField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('location', models.CharField(max_length=200)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Time')),
            ],
            options={
                'ordering': ('day',),
            },
        ),
    ]
