# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('M', 'Monday'), ('TU', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2),
        ),
    ]
