# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-18 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_auto_20180418_1843'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule_schedule',
        ),
        migrations.AlterModelTable(
            name='stop',
            table='schedule_stop',
        ),
        migrations.AlterModelTable(
            name='time',
            table='schedule_time',
        ),
    ]
