# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-19 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_pin_db_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='time',
            table=None,
        ),
    ]
