# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_pub_date', models.DateTimeField(verbose_name='date published')),
                ('news_description', models.TextField()),
            ],
        ),
    ]
