# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180215_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('news_pub_date',)},
        ),
    ]
