# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180215_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('pub_date',)},
        ),
        migrations.RenameField(
            model_name='new',
            old_name='news_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='news_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='news_title',
            new_name='title',
        ),
    ]
