# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_new_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.FileField(default='null', upload_to='news/'),
        ),
    ]
